---
- name: create mediawiki123 route
  openshift_v1_route:
    name: mediawiki123
    namespace: '{{ namespace }}'
    spec_port_target_port: web
    labels:
      app: mediawiki123
      service: mediawiki123
    to_name: mediawiki123
    state: present
  register: route

- name: create deployment config
  openshift_v1_deployment_config:
    name: mediawiki123
    namespace: '{{ namespace }}'
    labels:
      app: mediawiki123
      service: mediawiki123
    replicas: 1
    selector:
      app: mediawiki123
      service: mediawiki123
    spec_template_metadata_labels:
      app: mediawiki123
      service: mediawiki123
    containers:
    - env:
      - name: MEDIAWIKI_DB_SCHEMA
        value: "{{ mediawiki_db_schema }}"
      - name: MEDIAWIKI_SITE_NAME
        value: "{{ mediawiki_site_name }}"
      - name: MEDIAWIKI_SITE_LANG
        value: "{{ mediawiki_site_lang }}"
      - name: MEDIAWIKI_ADMIN_USER
        value: "{{ mediawiki_admin_user }}"
      - name: MEDIAWIKI_ADMIN_PASS
        value: "{{ mediawiki_admin_pass }}"
      - name: MEDIAWIKI_SITE_SERVER
        value: '{{ route.route.spec.host }}'
      image: docker.io/ansibleplaybookbundle/mediawiki123:latest
      name: mediawiki123
      ports:
      - container_port: 8080
        protocol: TCP
      volume_mounts:
        - mount_path: /persistent
          name: mediawiki123-volume
    volumes:
      - name: mediawiki123-volume
        persistent_volume_claim:
          claim_name: mediawiki123-pvc
