provision: mediawiki-apb
provision: ansibleplaybookbundle/postgresql-apb

bind: ansibleplaybookbundle/postgresql-apb
verify: rthallisey/service-broker-ci/verify-mediawiki-postgresql.sh

unbind: postgresql-apb | mediawiki-apb
deprovision: mediawiki-apb
deprovision: ansibleplaybookbundle/postgresql-apb
