provision: mediawiki123-apb
provision: rthallisey/service-broker-ci/postgresql

bind: rthallisey/service-broker-ci/postgresql
verify: rthallisey/service-broker-ci/verify-mediawiki-postgresql.sh
unbind: postgresql | mediawiki123-apb

deprovision: mediawiki123-apb
deprovision: rthallisey/service-broker-ci/postgresql
