provision: mediawiki-apb
provision: ansibleplaybookbundle/rhscl-postgresql-apb

bind: ansibleplaybookbundle/rhscl-postgresql-apb
verify: rthallisey/service-broker-ci/verify-mediawiki-postgresql.sh
unbind: postgresql | mediawiki-apb

deprovision: mediawiki-apb
deprovision: ansibleplaybookbundle/rhscl-postgresql-apb
