provision: mediawiki123-apb
provision: ansibleplaybookbundle/rhscl-postgresql-apb

bind: ansibleplaybookbundle/rhscl-postgresql-apb
verify: rthallisey/service-broker-ci/verify-mediawiki-postgresql.sh
unbind: postgresql | mediawiki123-apb

deprovision: mediawiki123-apb
deprovision: ansibleplaybookbundle/rhscl-postgresql-apb
