---

- name: "Update last operation"
  asb_last_operation:
    description: "0%: Starting"
  when: in_cluster

- name: 'Set facts'
  set_fact:
    cluster: '{{ "openshift" if "openshift" in lookup("k8s", cluster_info="version") else "kubernetes" }}'

- name: Validate Admin User and Password
  fail:
    msg: "Mediawiki Admin User and Password cannot be the same value!"
  when:
  - mediawiki_admin_user == mediawiki_admin_pass
  - apb_action == "provision"

- name: "Set mediawiki objects state={{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.apply | default(True)
  loop:
    - name: service.yaml.j2
    - name: pvc.yaml.j2
    - name: route.yaml.j2
      apply: "{{ True if cluster == 'openshift' else False }}"
    - name: deployment.yaml.j2

- name: "Update last operation"
  asb_last_operation:
    description: "100%: Done"
  when: in_cluster
