---

apiVersion: v1
kind: Route
metadata:
  name: {{ app_name }}
  namespace: {{ namespace }}
  labels:
    app: {{ app_name }}
    service: {{ app_name }}
spec:
  to:
    kind: Service
    name: {{ app_name }}
  port:
    targetPort: web
