---

apiVersion: {{ service_api_version }}
kind: Service
metadata:
  name: {{ app_name }}
  namespace : {{ namespace }}
  labels:
    app: {{ app_name }}
    service: {{ app_name }}
spec:
  ports:
    - name: web
      port: 8080
      target_port: 8080
  selector:
    app: {{ app_name }}
    service: {{ app_name }}
