- connection: local
  gather_facts: false
  hosts: localhost
  name: "Deprovision mediawiki-apb from {{ cluster }}"
  roles:
  - install_python_requirements: false
    role: ansible.kubernetes-modules
  - mediawiki
  vars:
    namespace: mediawiki-apb
    action: deprovision
