- name: mediawiki123-apb update
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - update-mediawiki123-apb
